name: Self Test

on:
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Get current time
        id: current_date_time
        uses: Kaven-Universe/github-action-current-date-time@v1.0.3
        with:
          format: "YYYY_MM_DD HH_mm_ss_SSS"
          timezone-offset: -480
      # Use the output from the `current_date_time` step
      - name: Get the output time
        run: echo "The time was ${{ steps.current_date_time.outputs.time }}"
